# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mp-icore.dtb \
			  imx8mm-icore-ctouch2.dtb \
			  imx8mm-icore-ctouch2-amp10.dtb \
			  imx8mm-icore.dtb \
			  imx8x-icore.dtb \
 	 		  imx8mp-smarcore.dtb \
 	 		  imx8mp-smarcore-hdmi.dtb
